
openapi: 3.0.3
info:
  title: Wallet management
  version: 1.0.1
  description: This spec manages wallet created by STD22057 and STD22006
servers:
  - url: https://management.wallet
tags:
  - Account
  - Transaction
paths:
  /account:
    get:
      tags:
        - Account
      summary: Get an Account by ID
      description: Return details of a specific account
      operationId: getAccountById
      parameters:
        - in: query
          name: id
          description: The ID of the account to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful retrieval of account data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

  /account{id}:
    put:
      tags:
        - Account
      summary: modify acount by ID
      description: Create if the account does not exist, otherwise update it
      operationId: accountId
      parameters:
        - in: query
          name: id
          required: true
          description: id of account modified
          schema:
            type: integer
      responses:
        '200':
          description: Successful modification of the account
        '201':
          description: account created successfully if it didn't exist before
        '400':
          description: Bad request, invalid input, or existing data conflict
        '404':
          description: account not found
  /transaction:
    get:
      tags:
        - Transaction
      summary: Get all transactions
      description: Return all transactions
      operationId: getAllTransactions
      parameters:
        - in: query
          name: id
          description: The ID of the account to get transactions for
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'

  /transaction/{id}:
    put:
      tags:
        - Transaction
      summary: Modify a transaction by ID
      description: Create if the transaction does not exist, otherwise update it
      operationId: transactionId
      parameters:
        - in: path
          name: id
          description: The ID of the transaction to modify
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Successful modification of the transaction
        '201':
          description: Transaction created successfully if it didn't exist before
        '400':
          description: Bad request, invalid input, or existing data conflict
        '404':
          description: Transaction not found

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        currency:
          type: string
        balance:
          type: double


    Transaction:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        amount:
          type: double
        type:
          type: string
        correspondent:
          type: string
