
openapi: 1.0.1
info:
  title: Wallet management
  version: 1.0.1
  description: This spec manages wallet created by STD22057 and STD2206
servers:
  - url: https://wallet.com
tags:
  - Account
  - Transaction
paths:
  /account:
     get:
       tags:
         - Account:
             summary: Get all Account by id
             description: The returned books are ordered by updated datetime.
             operationId: getAccountId
             parameters:
               in: path
               name: id
               description: the ID of the account to get
               required: true
               schema:
                 type: integer
             requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Account'
             responses:
               '200':
                 description: Successful retrieval of account data.


components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        currency:
          type: string
        balance:
          type: double


